apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: services-circuit-breaker
  namespace: cinemaabyss
spec:
  host: events-service
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: monolith-cb
  namespace: cinemaabyss
spec:
  host: monolith
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 7
      interval: 15s
      baseEjectionTime: 30s
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: movies-service-cb
  namespace: cinemaabyss
spec:
  host: movies-service
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 5s
      baseEjectionTime: 30s
